config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :profiles
  resources :blogs
  resources :websites

  get 'homes/index'

  get 'blogs/index', to: "blog#index"

  # get 'blogs/user/:id', to: "blogs#blog_user", as: "blog_user"

  # get 'websites/user/:id', to: "websites#website_user", as: "website_user"

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions', 
  # }

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "homes#index"
end

app/models/blog.rb
class Blog < ApplicationRecord
  include Visible
  belongs_to :user
  belongs_to :website
  after_create :blog_create


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	include ActionView::Helpers::DateHelper
	before_action :authenticate_user!
	helper_method :time_in_words

	def index
	    if params["blogs"] == 'all_blogs'
	      	@blogs = Blog.includes(:website).notice_visible
	    else
      		@blogs = current_user.blogs.includes(:website)
	    end
	end

	def new
		@blog = Blog.new
	end

	def create
		@blog = current_user.blogs.create(blog_params)
		
		if @blog.save

			redirect_to blogs_path
		else
			redirect_to new_blog_path
		end
	end

	def show
		@blog = Blog.find(params[:id])
	end 

	def blog_user
		@blogs = current_user.blogs
	end 	

	def edit
		@blog = Blog.find(params[:id])
	end

	def update
		@blog = Blog.find(params[:id])
		
		if @blog.update(blog_params)
			redirect_to :blog_user
		else 
			redirect_to :create
		end
	end	

	private

	def blog_params
		params.require(:blog).permit(:content, :website_id, :status)
	end

	def time_in_words(blog)
	 	created_time = blog.created_at
	 	time_ago_in_words(created_time)
	end
end

app/helpers/blogs_helper.rb
module BlogsHelper

	def time_in_words(blog)
	 	# created_time = blog.created_at
	 	# time_ago_in_words(created_time)
	end
	
end

app/views/blogs/blog_user.html.erb
<% @blogs.each do |blog|%>
<%= blog.content%><br>
<a href="<%= edit_blog_path(blog.id)%>">Edit Blog</a><br>
<% end %>

app/views/blogs/edit.html.erb
<%= form_for @blog do |b|%>
<%= b.label :content%>
<%= b.text_area :content%>
<%= b.submit %>
<% end %>

app/views/blogs/index.html.erb
<table>
<tr>
<th> Website URL</th>
<th> User ID </th>
<th> User Blog </th>
<th> Created at </th>
</tr>
<% @blogs.each do |f| %>
<tr>
<td><%= f.website.url%></td>
<td><%= f.user_id %></td>
<td><%= f.content%></td>
<td><%= time_in_words(f) %></td>
</tr>
<% end %>
</table>

app/views/blogs/new.html.erb
<%= form_for @blog do |b| %>

	<div class="field">
	<%= b.label :content %>
	<%= b.text_area :content %>
	<h3>select the album</h3>
<%=  collection_select(:blog, :website_id, Website.all , :id, :url) %><br>
	</div>

	<div>
		<%= b.label :status%>
		<%= b.check_box :status,{} ,'true '%>	
	</div>

	<div>
		<%= b.submit %>
	</div>
<% end %>