config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :profiles
  resources :blogs
  resources :websites

  get 'homes/index'

  get 'blogs/index', to: "blog#index"

  # get 'blogs/user/:id', to: "blogs#blog_user", as: "blog_user"

  # get 'websites/user/:id', to: "websites#website_user", as: "website_user"

  # devise_for :users, controllers: {
  #   sessions: 'users/sessions', 
  # }

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: "homes#index"
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li><%= "Hi, #{current_user.username}" %></li>

    	<%if current_user.profile.nil?%>
    		<li><%= link_to "Create Profile",  new_profile_path%></li>
    	<%else %>
    		<li><%= link_to "Edit Profile",  edit_profile_path(current_user.id)%></li>
    	<%end%>

      <li><%= link_to "Show all Profiles", profiles_path  %></li>

      <%if current_user.address.nil?%>
        <li><%= link_to "Create Address",  new_address_path%></li>
      <%else%>
        <li><%= link_to "Edit Address",  edit_address_path(current_user.address.id)%></li>
      <%end%>
      
      <li><%= link_to "Insert Website",  new_website_path%></li>

      <%if current_user.websites != []%>
        <li><%= link_to "Show Website", websites_path%></li>
      <%end%>
      
      <%if current_user.blogs != []%>
        <li><%= link_to 'Show My Blogs', blogs_path(:blogs => 'my_blogs') %></li>
      <% end %>

    <li><%= link_to 'Show All Blogs', blogs_path(:blogs => 'all_blogs') %></li>
    <li><%= link_to "Create Blog", new_blog_path(current_user.id)%></li>
    <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
  <% else %>
	<li><%= link_to 'Sign In', new_user_session_path %></li>
	<li><%= link_to 'Sign Up', new_user_registration_path %></li>
  <li><%= link_to 'Sign in with github', user_github_omniauth_authorize_path, method: :post %></li>
  <li><%= link_to 'Sign Up with github', user_github_omniauth_callback_path , method: :post%></li>
  <% end %>
</ul>